### ISSUE TITLE
Draft: Add CI workflow

### ISSUE THREAD

**Issue by cyrdam** [cyrdam/lerna-monorepo-starter#17]
# Add a CI pipeline to the project.

> Note: Missing a CI/CD is not an issue for this starter, but it could help out in the long run for others.

The repository is not complete, and could make things difficult for a more complete starter, meaning:

- there are no tests in the repository, and running the test command fails
- there are no build steps

Looking from this point it could only use following parts for testing:

- install dependencies successfully
- run lint successfully
- let `npm run test` return a warning or no error, rather breaking the pipeline

Mainly this repository will handle two CI providers:

- GitHub
- GitLab

## Tasks

- prepare steps
  - [x] fix test command
- [x] Add GitHub Actions
  - Create CI steps
    - [x] installation
    - [x] lint
    - [x] test
- [ ] Add GitLab CI
  - Create CI steps
    - [ ] installation
    - [ ] lint
    - [ ] test

## Additional notes

Each of the tasks points should have it's own merge request. Make the steps as small as possible

**Comment by cyrdam** [comment]
Update:

- Set errors to code 0, not breaking the tests
- GitHub Actions included and running green
